### ISSUE TITLE
Builds failing with strange class not found error for closure

### ISSUE THREAD

**Issue by moly** [gradle/gradle#11970]
### Expected Behavior
Build completes successfully

### Current Behavior
Builds failing with error
```
A problem occurred evaluating root project 'hydra'.
> build_e8txdpm1pdbl1qtevmy32q67e$_run_closure1$_closure6$_closure7
```

### Context
I'm using gradle to compile a java project. On my local machine, everything seems to work fine. However, when building on an internal gitlab ci server, after a few successful builds it will start failing with the above error.
If I enable `--stacktrace`, the cause is:
```
2020-01-22T12:20:45.558+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: java.lang.ClassNotFoundException: build_awsefijylijhxywzs5ijcqtom$_run_closure1$_closure6$_closure7
2020-01-22T12:20:45.558+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.groovy.scripts.internal.DefaultScriptCompilationHandler$ScriptClassLoader.loadClass(DefaultScriptCompilationHandler.java:382)
```
Full stacktrace here: https://gist.github.com/moly/3788ff80be1387d4cec03494bf9e4829

I can temporarily fix it by deleting .gradle/caches, but after a few builds the error will appear again.

The error looks very similar to https://discuss.gradle.org/t/strange-class-not-found-error-for-closure/18982, which was apparently fixed years ago.

### Steps to Reproduce 
Unfortunately I've not been able to reproduce this locally. It happens very predictably on my ci server though.
build.gradle: https://gist.github.com/moly/ee2f77c39d606eca0a0e9068a66fdb04

.gitlab-ci.yml:
```
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"

cache:
  paths:
    - .gradle/caches
    - .gradle/wrapper
    - .gradle/notifications

build:
  stage: build
  script:
    - gradlew --build-cache assemble
```

### Your Environment
Operating system | Windows Server 2016 10.0 
-- | --
CPU cores | 4 cores 
Max Gradle workers | 4 workers 
Java runtime | Oracle Java(TM) SE Runtime Environment 1.8.0_162-b12 
Java VM | Oracle Java HotSpot(TM) 64-Bit Server VM 25.162-b12 (mixed mode) 
Max JVM memory heap size | 7635 MB 
Locale | English (United States) 
Default charset | windows-1252
