### ISSUE TITLE
using "publishToMavenLocal()" in Github Actions

### ISSUE THREAD

**Issue by Papashkin** [gradle/gradle#13337]
Hello!

I'm working with library for Android project in private repo, and want to publish it last version into mavenLocal via CI/CD tool Github Actions.
I have a *.yml file for CI/CD:
```
on:
  push:
    branches: [ master, develop ]

jobs:
  build:
    name: Publish AAR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Publish to MavenLocal
        run: ./gradlew publishToMavenLocal
```

### Expected Behavior

After pull-request merging I expect that my last updates will be in the next AAR of lib.
### Current Behavior
I don't see last updates in my project after Gradle syncing.

### Context

I wrote this code which allows me to publish AAR to `mavenLocal`:
```
afterEvaluate {
        publishing {
            publications {
                library(MavenPublication) {
                    from components.release
                    groupId = libGroupName
                    artifactId = libArtifactName
                    version = libArtifactVersion
                }
            }
        }
    }
```
Of course, I applied a Maven publish plugin:
```
apply plugin: 'maven-publish'
```
When I'm in Library project and launch `publishToMavenLocal` script manually, it works. But I want to use it also in CI/CD.
### Your Environment

Android Studio version: 3.6.1
Gradle plugin for Android Studio version: 3.6.3
Gradle version: 5.6.4
