### ISSUE TITLE
excludePlugin in version catalog does not work

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#16079]
Given:
`gradle/dependencies1.toml`:
```toml
[plugins]
org.jetbrains.kotlin.jvm = "1.4.30"
```
`gradle/dependencies2.toml`:
```toml
[plugins]
org.jetbrains.kotlin.jvm = "1.4.20"
```
`settings.gradle.kts`:
```kts
dependencyResolutionManagement {
    versionCatalogs {
        create("libs") {
            from(files("gradle/dependencies1.toml")) {
                excludePlugin("org.jetbrains.kotlin.jvm")
            }
        }
        create("libs2") {
            from(files("gradle/dependencies2.toml"))
        }
    }
}
````

Expected behaviour:
default plugin version is 1.4.20

Actual behaviour:
```
java.lang.IllegalArgumentException: Cannot provide multiple default versions for the same plugin.
> Cannot provide multiple default versions for the same plugin.
```
