### ISSUE TITLE
Version Catalog API: Dependency classifier can not be specified?

### ISSUE THREAD

**Issue by jnehlmeier** [gradle/gradle#17169]
I have projects that explicitly depend on Java sources but currently it seems impossible to declare a dependency classifier in the Version Catalog API / toml file.

### Expected Behavior
```toml
[versions]
some-lib-version = "1.0.0"

[libraries]
some-lib = { module = "com.example:some-lib", version.ref = "some-lib-version" }
# We need sources as well
some-lib-sources = { module = "com.example:some-lib", classifier = "sources", version.ref = "some-lib-version" }
# or possibly shorter syntax
some-lib = { module = "com.example:some-lib:sources", version.ref = "some-lib-version" }
# or possibly even shorter syntax
some-lib ="com.example:some-lib:${some-lib-version}:sources"
```
