### ISSUE TITLE
Add best practices for CI to Idiomatic Gradle documentation

### ISSUE THREAD

**Issue by runningcode** [gradle/gradle#17511]
It is often asked how to configure Gradle best for CI builds. What are the best practices?
Much of this information is available in different parts of the user manual, but it would be good to sum it up in a single place.

Here are some example questions:
* Should the local build cache be used?
* Should configuration cache be enabled?
* How should I share my dependency cache?
* Should the Gradle Daemon be enabled?
* Should I use an ephemeral CI?
* Should I run the `clean` task?

**Comment by matthewadams** [comment]
@runningcode Can you please provide those answers here in the meantime?  We're wasting ~2 minutes on every gitlab ci pipeline waiting for the daemon to start.

**Comment by matthewadams** [comment]
We're using the strategy of defining our own Docker image that's `FROM gradle:jdk16`, doing a test compile in it to download all dependencies so they're baked into the image, then using that image for our builds.  Here's the Dockerfile we use to prebuild our CI image:
```
FROM gradle:jdk16

COPY *.gradle.kts ./
COPY src ./src
RUN gradle --no-watch-fs testClasses
RUN gradle --stop
RUN rm -rf src
```
Here's our `.gitlab-ci.yml` job to create the prebuild Dockerfile:
```yaml
prebuild-image:
  stage: prebuild
  services:
    - docker:20.10.8-dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - export BASE_IMAGE_NAME="$CI_PROJECT_NAME-$CI_COMMIT_REF_NAME"
    - export FULL_IMAGE_NAME="$CI_REGISTRY_IMAGE/$BASE_IMAGE_NAME"
    - docker build -f prebuild.Dockerfile -t "$CI_REGISTRY_IMAGE/$BASE_IMAGE_NAME" --build-arg BUILDKIT_INLINE_CACHE=1 .
    - docker push "$CI_REGISTRY_IMAGE/$BASE_IMAGE_NAME"
  only:
    changes:
      - prebuild.Dockerfile
      - build.gradle.kts
      - settings.gradle.kts
```
It takes ~2 minutes each time to start the gradle daemon:
![image](https://user-images.githubusercontent.com/449952/135508585-4f4d0c2e-b519-41ff-a9a5-54eff3c2d47c.png)

I've confirmed that our downloaded dependencies aren't being redownloaded (at least, I _think_ I have) based on messages like this:
```
Found locally available resource with matching checksum: [https://repo.maven.apache.org/maven2/com/fasterxml/jackson/core/jackson-core/2.12.3/jackson-core-2.12.3.module, /home/gradle/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-core/2.12.3/d72376bded4e50d77f700d2486ada7f15796f446/jackson-core-2.12.3.module]
```
