### ISSUE TITLE
Version Catalog: Sub-accessors and alias overload not supported for plugins.

### ISSUE THREAD

**Issue by rnett** [gradle/gradle#18142]
### Expected Behavior
I have plugin definitions `kotlin-js` and `kotlin-js-action`.  As of 7.2, this works fine for libraries, and I expected it to work for plugins, too.

### Current Behavior
I get:
```
Script compilation error:

  Line 5:     alias(libs.plugins.kotlin.js) apply false
                    ^ Type mismatch: inferred type is LibrariesForLibs.KotlinJsPluginAccessors! but Provider<PluginDependency!>! was expected
```

### Context
This is an annoyance whenever you want to use plugins where one has an ID containing the other's ID.  This likely won't be very common, but I would think it's doable since it's done for dependencies.

### Steps to Reproduce 
Use `libs.versions.toml`:
```toml
[versions]
kotlin = "1.5.21"
kotlin-js-action = "1.4.3"

[plugins]
kotlin-js = { id = "org.jetbrains.kotlin.js", version.ref = "kotlin" }
kotlin-js-action = { id = "com.github.rnett.ktjs-github-action", version.ref = "kotlin-js-action" }
```

Use `build.gradle.kts`:
```kotlin
plugins {
    alias(libs.plugins.kotlin.jvm) apply false
    alias(libs.plugins.kotlin.js) apply false
}
```

### Your Environment
Windows, Gradle 7.2.
