### ISSUE TITLE
[7.2] Start script stopped expanding environment variables passed inside JAVA_OPTS 

### ISSUE THREAD

**Issue by deejay1** [gradle/gradle#18170]
Gradle 7.2 start script stopped expanding environment variables passed inside JAVA_OPTS 

### Expected Behavior
Gradle should expand further environment variables passed inside JAVA_OPTS, so one can pass additional runtime information, for example a kubernetes POD_IP (like `-Djava.rmi.server.hostname=$POD_IP`) or other potential information from the environment.

### Current Behavior
Currently those variables are quoted, and passed as is to the JRE, which results in errors like 

```java
jdk.internal.agent.AgentConfigurationError: java.lang.NumberFormatException: For input string: "$PORT"
```

### Steps to Reproduce 
```bash
export PORT=1234
export JAVA_OPTS='-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=$PORT -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false'
...make a start script and run it...
```
results in
```java
Error: Invalid com.sun.management.jmxremote.port number: $PORT
jdk.internal.agent.AgentConfigurationError: java.lang.NumberFormatException: For input string: "$PORT"
	at jdk.management.agent/sun.management.jmxremote.ConnectorBootstrap.startRemoteConnectorServer(ConnectorBootstrap.java:337)
	at jdk.management.agent/jdk.internal.agent.Agent.startAgent(Agent.java:447)
	at jdk.management.agent/jdk.internal.agent.Agent.startAgent(Agent.java:599)
Caused by: java.lang.NumberFormatException: For input string: "$PORT"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:638)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at jdk.management.agent/sun.management.jmxremote.ConnectorBootstrap.startRemoteConnectorServer(ConnectorBootstrap.java:335)
	... 2 more
```

or have the following part in Kubernetes pod config

```yaml
-env:
  - name: JAVA_OPTS
     value: -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=$PORT -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false
  - name: PORT
     value: 1234
```
