### ISSUE TITLE
VERSION_CATALOGS support for platform (BOM)

### ISSUE THREAD

**Issue by Fleshgrinder** [gradle/gradle#19142]
### Context
I was defining a dependency on `software.amazon.awssdk:acmpca` and it pulled totally invalid transitive dependencies in. No idea if Maven would have worked correctly here, and it doesn't matter. Fact is that the inclusion of the BOM fixed it.

> I couldn't find an issue here nor in Slack, but maybe my search-fu is not good enough and this was already discussed. I'm sorry if that's the case.

### Expected Behavior
Dependencies can be defined as platform and are recognized as such automatically, especially to create bundles.

```toml
[versions]
aws-sdk = "2.17.89"

[libraries]
aws-sdk-bom = { module = "software.amazon.awssdk:bom", version.ref = "aws-sdk" }
aws-sdk-acmpca = { module = "software.amazon.awssdk:acmpca" }
```

```kotlin
dependencies {
    implementation(platform(libs.aws.sdk.bom))
    implementation(libs.aws.sdk.acmpca)
}
```

### Current Behavior
It is not possible to define a dependency as platform, but that would be very useful. I don't know what the best way would be to add this functionality to the TOML, but the usage is clear.

```toml
[versions]
aws-sdk = "2.17.89"

[platforms]
aws-sdk-bom = { module = "software.amazon.awssdk:bom", version.ref = "aws-sdk" }

[libraries]
aws-sdk-acmpca = { module = "software.amazon.awssdk:acmpca" }

[bundles]
aws-sdk = ["aws-sdk-bom", "aws-sdk-acmpca"]
```

```kotlin
dependencies {
    implementation(libs.bundles.aws.sdk)
}
```
