### ISSUE TITLE
Consider stopping GitHub Actions jobs on stale commits

### ISSUE THREAD

**Issue by TWiStErRob** [gradle/gradle#19173]
cc @JLLeitschuh and @wolfs as majority contributors on [.github/workflows](https://github.com/gradle/gradle/commits/master/.github/workflows).

I've noticed that pushing multiple times to the same forked PR branch will trigger builds for every single commit. Most of the time I'm just fighting with DCO signoffs, but even in other cases if there's a later commit the old ones are not really worth building.

### Expected Behavior
Later pushes could stop earlier builds. This would save resources, might reduce Gradle GitHub costs, and also hopefully slightly affect the environment as well considering the scale of this repo.

### Current Behavior
Each push to a PR will trigger a GitHub Actions build.
https://github.com/gradle/gradle/actions?query=branch%3Astartparams
(1444, 1445 and 1446 were 3 quick pushes trying to satisfy DCO)

### Context
Docs: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#concurrency

For example this is what I'm using in most of my projects:
```yaml
on:
  push
concurrency:
  # Documentation suggests ${{ github.head_ref }}, but that's only available on pull_request/pull_request_target triggers, so using ${{ github.ref }}.
  # On master, we want all builds to complete even if merging happens faster to make it easier to discover at which point something broke.
  # More info: https://stackoverflow.com/a/68422069/253468:
  group: ${{ github.ref == 'refs/heads/master' && format('ci-master-{0}', github.sha) || format('ci-{0}', github.ref) }}
  cancel-in-progress: true
```
(replace `ci-` in both places with the name of the workflow to prevent cross-cancellations)
