### ISSUE TITLE
Provisioned toolchain Java 17 could not be probed.

### ISSUE THREAD

**Issue by akefirad** [gradle/gradle#19507]
My build job on AWS CodeBuild suddenly started failing with the error:
```
Downloading https://services.gradle.org/distributions/gradle-7.3.2-bin.zip
--
64 | ...........10%...........20%...........30%...........40%...........50%...........60%...........70%...........80%...........90%...........100%
65 |  
66 | Welcome to Gradle 7.3.2!
67 |  
68 | Here are the highlights of this release:
69 | - Easily declare new test suites in Java projects
70 | - Support for Java 17
71 | - Support for Scala 3
72 |  
73 | For more details see https://docs.gradle.org/7.3.2/release-notes.html
74 |  
75 | To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/7.3.2/userguide/gradle_daemon.html#sec:disabling_the_daemon.
76 | Daemon will be stopped at the end of the build
77 |  
78 | FAILURE: Build failed with an exception.
79 |  
80 | * What went wrong:
81 | Could not determine the dependencies of task ':bootJar'.
82 | > Could not resolve all dependencies for configuration ':runtimeClasspath'.
83 | > Failed to calculate the value of task ':compileJava' property 'javaCompiler'.
84 | > Provisioned toolchain '/root/.gradle/jdks/jdk-17.0.1+12' could not be probed.
```
### Expected Behavior
The build should proceed by downloading the specified toolchain.

### Current Behavior
It fails to "probe" the "provisioned toolchain".

### Context
NOTE: the issue is NOT reproducible locally or on AWS CodeBuild locally (with Amazon Linux 2). Our build job are using Ubuntu.
Also, the build job used to work previously and started failing today.
It's pretty similar to #17565 but for Java 17 and also I didn't specify any vendor, just Java version.
BTW, removing `~/.gradle/jdks` folder didn't help (as I found it somewhere as a solution)
I'm not sure this is an issue for Gradle or AWS CodeBuild, TBH.

### Steps to Reproduce 
1. Create a simple Gradle app (use start.spring.io or download [demo.zip](https://github.com/gradle/gradle/files/7829786/demo.zip))
2. Create a simple AWS CodeBuild with the given details above and add a simple spec to build the project:
```yaml
version: 0.2
env:
  shell: bash
  git-credential-helper: yes
  variables:
    GRADLE_USER_HOME: /root/.gradle
    GRADLE_OPTS: >
      -Dgradle.user.home=/root/.gradle
      -Dorg.gradle.console=plain
      -Dorg.gradle.daemon=false
      -Dorg.gradle.caching=true
      -Dorg.gradle.vfs.watch=false
phases:
  install:
    runtime-versions:
      java: corretto11.x
  build:
    commands:
      - ./gradlew build
```
3. And run the build project.

### Your Environment
Build Env: AWS CodeBuild, Image: `aws/codebuild/standard:5.0`, latest version (after `21.01.08`, since for the old version it seems it's working)
Build scan URL: https://scans.gradle.com/s/nk5qqxfwhqv3o
