### ISSUE TITLE
Version catalog should support because/reason like dependency constraints

### ISSUE THREAD

**Issue by dawi** [gradle/gradle#19517]
Gradle allows to define a reason for dependency constraints like this:

```kotlin
dependencies {
    constraints {
        api("org.apache.logging.log4j: core") {
            version {
                strictly("[2.17,3[")
                prefer("2.17.1")
            }
            because("CVE-2021-44228, CVE-2021-45046, CVE-2021-45105: Log4j vulnerable to remote code execution and other critical security vulnerabilities.")
        }
    }
}
```

which results in the following `module.json`:

```json
{
  "group": "org.apache.logging.log4j",
  "module": "log4j-jul",
  "version": {
    "strictly": "[2.17,3[",
    "requires": "[2.17,3[",
    "prefers": "2.17.1"
  },
  "reason": "CVE-2021-44228, CVE-2021-45046, CVE-2021-45105: Log4j vulnerable to remote code execution and other critical security vulnerabilities."
}
```

Now I would like to express the same information in a version catalog and use this information inside the dependency constraints.

```toml
[versions]
log4j = { strictly = "[2.17,3[", prefer = "2.17.1", because="CVE-2021-44228, CVE-2021-45046, CVE-2021-45105: Log4j vulnerable to remote code execution and other critical security vulnerabilities." }
[libraries]
log4j-core = {module ="org.apache.logging.log4j:log4j-core", version.ref = "log4j"}
```

```kotlin
dependencies {
    constraints {
        api(libs.log4j)
    }
}
```

However, [according to the documentation](https://docs.gradle.org/current/userguide/platforms.html#sub:conventional-dependencies-toml), only the following properties are supported:

* require: the required version
* strictly: the strict version
* prefer: the preferred version
* reject: the list of rejected versions
* rejectAll: a boolean to reject all versions

As a result I ended up with the following solution. 

```toml
[versions]
log4j = { strictly = "[2.17,3[", prefer = "2.17.1"}
[libraries]
log4j-core = {module ="org.apache.logging.log4j:log4j-core", version.ref = "log4j"}
```

```kotlin
dependencies {
    constraints {
        api(libs.bundles.log4j) {
            because("CVE-2021-44228, CVE-2021-45046, CVE-2021-45105: Log4j vulnerable to remote code execution and other critical security vulnerabilities.")
        }
    }
}
```

Now I have two points:

1. Shouldn't the because/reason be part of the dependency version as well?
Maybe there are architectural reasons, to not store that information in the version catalog, but for me as an end user it does not feel right that I have to document the reason for a certain version decision somewhere else.
2. The `libs.versions.toml` should be validated to throw an error, if unsupported properties are used.
