### ISSUE TITLE
Bad clean build performance

### ISSUE THREAD

**Issue by IRus** [gradle/gradle#19565]
I'm using Gradle for years with Gradle Kotlin DSL currently, and recently convinced team to migrate all projects from maven to Gradle. What I observed on CI – build time of clean build (no caches, nor CI nor remote) almost two times slower than maven.

### Expected Behavior
We're using gitlab CI for building small library (about 100 classes), maven build takes about 40-80s, gradle build 120-180s. 

### Context
We're using official gradle image 7.3.3-jdk11.
settings.gradle.kts just defines rootProject.name and build scan plugin
build.gradle.kts has three plugins: java, maven-publish and net.researchgate.release. dependencies, publishing and release blocks. 

After introducing cache in gitlab: 

```
before_script:
  - export GRADLE_USER_HOME="$(pwd)/.gradle"

cache:
  key:
    files:
      - gradle/wrapper/gradle-wrapper.properties
  paths:
    - .gradle/wrapper
    - .gradle/caches
```

Build becomes much faster. But it's adding costs of downloading/saving cache. Overall time about 60-80s (not so bad, but not as fast as maven). 

I assume that there are two "slow" task happens:

1. Compiling kts files (K2 compiler should improve this)
2. Generating(?) gradle-api 150mb jar
3. Generating accessors based on plugins

I believe for point 1 we can't do much about, but points 2 and 3 can be optimized by: including gradle-api jar in base image and downloading pre-build accessors for known plugins.

### Steps to Reproduce
Create basic project in clean environment and build it

### Your Environment
Build scan URL:
* no cache build https://scans.gradle.com/s/oiphte5cbdu4q
* gitlab cache build https://scans.gradle.com/s/bhsbob6qskvb4 (just gradle build, not gradle clean build*)
