### ISSUE TITLE
Unable to resolve AAR library from Jitpack with Version Catalog

### ISSUE THREAD

**Issue by ghostbear** [gradle/gradle#20074]
I'm having this problem with being unable to resolve two dependencies with Version Catalog.

Then when I try syncing I get the error `Unable to resolve dependency for...`

When running `./gradlew check --warning-mode all` I get this 

![image](https://user-images.githubusercontent.com/6576096/156563839-d57d6991-ee58-49ef-a829-12776e51c179.png)

Work fine if imported without Version Catalog but fails when in Version Catalog

### Expected Behavior
Being able to resolve AAR libraries

### Current Behavior
Not being able to resolve AAR libraries

### Context

Check above `Expected Behavior`

### Steps to Reproduce 
Have libraries that specify `@arr`, like these two
```toml
storio-common = "com.github.inorichi.storio:storio-common:8be19de@aar"
storio-sqlite = "com.github.inorichi.storio:storio-sqlite:8be19de@aar"
```

Then import them into any module

### Your Environment

Build scan URL: https://scans.gradle.com/s/45jtqeio4vxai
