### ISSUE TITLE
Would it be possible to cache gradle daemon to a file to speed up ephemeral CI/CD docker images?

### ISSUE THREAD

**Issue by AkselAllas** [gradle/gradle#20449]
In a persistant VM I can get my gradle build process down to 6-12 sec thanks to Gradle daemon already running.

In an ephemeral CI/CD Docker container (Github Actions) my build takes 1min29 sec due to Gradle daemon needing to start up.

Would it be possible to write a custom optional flag which would try to cache the Gradle daemon to a file, which could be passed as an artifact between the CI/CD pipeline runs?

**Comment by asodja** [comment]
Did you try Gradle GitHub action `gradle/gradle-build-action@v2`?

It should automatically cache cachable things between builds and it might solve your issue.  Check [README](https://github.com/gradle/gradle-build-action#caching) for details.

**Comment by AkselAllas** [comment]
I read that gradle-build-action@v2 uses `--no-daemon` and as such doesn't cache the daemon itself.

https://github.com/gradle/gradle-build-action/issues/113

**Comment by asodja** [comment]
I would still suggest trying with the `gradle/gradle-build-action@v2`. 

I think slowness comes from the fact that `Gradle` on the very first start does some extra work, like generating some jars etc, that might take some time. And I believe `gradle-build-action` caches that, so the very first start is slow but all next starts of a daemon should be faster.

Note that daemon is a process and as such, saving it to a file is not that easy. We would have to save all its state to a file for example.

**Comment by AkselAllas** [comment]
I have tried [actions/cache](https://github.com/actions/cache/blob/main/examples.md#java---gradle) and [gradle-build-action](https://github.com/gradle/gradle-build-action#caching) and [setup-java](https://github.com/actions/setup-java)

Every result is roughly 1min30sec

Example of uses:

```
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
```

```
      - name: Cache Gradle packages and Google Jib cache
        uses: actions/cache@v3
        with:
         path: |
          ~/.gradle
          ~/.cache/google-cloud-tools-java/jib
         key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle.kts') }}
         restore-keys: ${{ runner.os }}-gradle
```

**Comment by AkselAllas** [comment]
My analysis is still that it's the in-memory daemon that is the limiting factor.

**Comment by AkselAllas** [comment]
I also tried:

```
      - name: Setup java
        uses: actions/setup-java@v2
        with:
        distribution: temurin
        java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
```

Setup java takes 0 sec :D and pipeline is still 1min30sec

**Comment by asodja** [comment]
Sorry that you are seeing these issues, I could always be wrong here.

I tried with a dummy Gradle project. I had a very basic setup:
```
name: Build Gradle project
on:
  push:
jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v2
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        run: ./gradlew build
```
and first-run took cca. [1m](https://github.com/asodja/gradle-constants-test/actions/runs/2165948528/attempts/1), while the second attempt was  [22s](https://github.com/asodja/gradle-constants-test/actions/runs/2165948528/attempts/2).

And Gradle part (starting daemon, running tests) of the second attempt was 13s.
<img width="1617" alt="Screenshot 2022-04-14 at 10 06 17" src="https://user-images.githubusercontent.com/3939893/163342002-13da8e8d-ad1a-47e5-bfa8-dfaff714fdf0.png">

So from that I believe daemon start-up is not an issue. But I see that there might be some other issue in the play for your case (maybe compiling build logic/scripts takes long?). But it's difficult to say what is an issue without a producer. 

Maybe it would be worth to ask also on the [community Slack channel](https://gradle.com/slack-invite) if anyone from the community that works with GitHub actions regularly would give a hint.
