### ISSUE TITLE
Version Catalog TOML: Version Reference Support for strictly, required, etc.

### ISSUE THREAD

**Issue by sskrla** [gradle/gradle#21544]
### Expected Behavior
When defining a version catalog with TOML, it would be helpful to allow version restrictions to also use `ref`. For example, a project may require that Zookeeper strictly adhere to a specific version due to the service deployment.

```toml
[versions]
zookeeper = "3.5.7"

[libraries]
zookeeper = { module = "org.apache.zookeeper:zookeeper", version.strictly.ref = "zookeeper" }
zookeeper-jute = { module = "org.apache.zookeeper:zookeeper-jute", version.strictly.ref = "zookeeper" }
```

### Current Behavior
Gradle will complain that:  `org.tomlj.TomlInvalidTypeException: Value of 'strictly' is a table`. And indeed, the parser expects `strictly`, `require`, etc. be a version string.

### Context
As mentioned above, we need to strictly control client libraries for services that may be very sensitive to protocol versions, and occasionally we require several dependencies of the same version. Alternatively, it may be important to call out the version as being important at the top of the file in the version table.
