### ISSUE TITLE
Support platform (BOM) dependencies

### ISSUE THREAD

**Issue by pablofanatics** [gradle/gradle#23346]
Currently, it can be easy to forget or not know that we have to add platform (BOM) dependencies for different configurations. 

We have several options to make it easier:

A) Add an extra dependency handler for bom files.
B) Make sure implementation platform dependencies are propagated to other handlers.

### Expected Behavior
If we create a special case for bom dependencies we could have:

```kotlin
dependencies {
  platform(libs.compose.bom)
  implementation(libs.ui)
  implementation(libs.ui.test.junit4)
}
```

or 

```kotlin
dependencies {
  bom(libs.compose.bom)
  implementation(libs.ui)
  implementation(libs.ui.test.junit4)
}
```

### Current Behavior

```kotlin
dependencies {
  implementation(platform(libs.compose.bom))
  implementation(libs.ui)

  testImplementation(platform(libs.compose.bom))
  implementation(libs.ui.test.junit4)
}

```

### Context

I had this in my dependency toml file:

```toml
[versions]
# ...
composeBom = "2022.12.00"
# ...
[libraries]
# ...
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
# ...
ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
# ...
```

And then, I was applying the compose bom like this (omitting some of the `implementation` dependencies):

```kotlin
implementation(platform(libs.compose.bom))
// ...
androidTestImplementation(libs.ui.test.junit4)
```

I was getting the following error:

```bash
Execution failed for task ':androidApp:processDevDebugAndroidTestManifest'.
> Could not resolve all files for configuration ':androidApp:devDebugAndroidTestRuntimeClasspath'.
   > Could not find androidx.compose.ui:ui-test-junit4:.
     Required by:
         project :androidApp
```

Which made me revert to applying the dependency without the type safety:

```kotlin
androidTestImplementation("androidx.compose.ui:ui-test-junit4:1.3.2")
```

Then, I found this issue that got me to the fact that I had to apply the bom on all configurations in order to include the versions.
https://issuetracker.google.com/issues/257107006

And I was able to use the version catalogue for tests too 🥳
