### ISSUE TITLE
Foreign dependency declaration in Version Catalog

### ISSUE THREAD

**Issue by bric3** [gradle/gradle#23523]
My gradle build is depending on resources that are not part of the java ecosystem, JS libraries, fonts, among others. These resources are fetched by custom script or plugins.

The resources of these plugins can be expressed as properties, but I believe the _version catalog_, and the associated TOML, could be a good place to see all dependencies as a whole.

However the TOML and possibly the machinery do not accept _custom_ property declarations. E.g.

```toml
# Regular TOML sections

[versions]
bytebuddy = "1.12.21"

[libraries]
bytebuddy = { group = "net.bytebuddy", name = "byte-buddy", version.ref = "bytebuddy" }
bytebuddy-agent = { group = "net.bytebuddy", name = "byte-buddy-agent", version.ref = "bytebuddy" }

[bundles]
bytebuddy = ['bytebuddy', 'bytebuddy-agent']

[plugins]
download = { id = "de.undercouch.download", version = "5.3.0" }

###########

# Foreign declarations

[js]
pegjs = { url = "https://cdn.jsdelivr.net/npm/peggy@2.0.1/browser/peggy.min.js", sri = "sha256-rc8x8rCn3MX/3jqUGfnqeIurZfNJY2vuHuoP7UfQyV8=" }
```

### Expected Behavior

I believe the version catalog mechanism could be more lenient and / or plugable

1. If the approach is to make the _version catalog_ plugable then a plugin would be able to register sections, and handle the parsing of this section, the plugin implementation can then choose how to make this data available to the build script.

   In this approach if the plugin is not registered I suppose the parser could ignore _foreign_ sections (i.e. section not named `bundles`, `libraries`, `metadata`, `plugins` or `versions`), so in the example above `js` will be ignored.

2. If the approach is to make the _version catalog_ generate "accessors" from the foreign section, e.g. for the following entry :

   ```toml
   pegjs = { url = "https://cdn.jsdelivr.net/npm/peggy@2.0.1/browser/peggy.min.js", sri = "sha256-rc8x8rCn3MX/3jqUGfnqeIurZfNJY2vuHuoP7UfQyV8=" }
   ```

   the parser should generate the following:

   ```kotlin
   libs.js.pegJs.url (String)
   libs.js.pegJs.sri (String)
   ```

   This approach could also be a plugin.

### Current Behavior

Currently the parser is strict about non supported sections.

```
java.lang.RuntimeException: org.gradle.api.InvalidUserDataException: Invalid TOML catalog definition:
  - Problem: In version catalog libs, unknown top level elements [js].
    
    Reason: TOML file contains an unexpected top-level element.
    
    Possible solution: Make sure the top-level elements of your TOML file is one of 'bundles', 'libraries', 'metadata', 'plugins' or 'versions'.
```

**Comment by melix** [comment]
There is a major drawback in supporting something like this, which is that it basically breaks tooling. One of the design reasons for catalogs was tooling support and the fact that the file format is standardized. If we can add arbitrary sections in a TOML file, then consumers cannot know how to interpret it.

**Comment by bric3** [comment]
I didn't considered that point. As I imagined tools to only look at _standard_ Gradle sections.

In that case I wonder if Gradle could offer the same feature (i.e. generating "accessors") from a different source e.g. `lib.js.toml`.

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

This feature request is in the backlog of the relevant team but this area of Gradle is currently not a focus one so it might take a while before it gets implemented.

**Comment by bric3** [comment]
Yes sure @jbartok , thank you for reaching back !

**Comment by andrew-k-21-12** [comment]
Just would like to upvote the request. My use case exploits Kotlin/JS, as a workaround it's only possible to use the following declarations (there is no way to omit an unneeded group):

```toml
[versions]
html-webpack = "5.5.0"

[libraries]
html-webpackplugin = { group = "jantimon", name = "html-webpack-plugin", version.ref = "html-webpack" }
```

and usages:

```kotlin
implementation(devNpm(jsLibs.html.webpackplugin.get().name, jsLibs.html.webpackplugin.get().version!!))
```
