### ISSUE TITLE
Test suite cannot add bundle from version catalog

### ISSUE THREAD

**Issue by VictorCardona75** [gradle/gradle#23605]
### Expected Behavior
Test suites should be able to use bundles from version catalogs. See #18632

### Current Behavior
Build script fails to compile when attempting to add a dependency to a bundle.

### Context
I'm working on a Kotlin project that has a bundle of related testing libraries defined.  I want to add a dependency on that bundle to the default test suite, or to every test suite if more than one are declared.

I was able to workaround the issue, and have included the workaround in the example below.

**libs.versions.toml**
```toml
[versions]
kotest = "5.5.4"

[libraries]
kotest-framework = {module = "io.kotest:kotest-runner-junit5", version.ref = "kotest"}
kotest-datatest = {module = "io.kotest:kotest-framework-datatest", version.ref = "kotest"}
kotest-assertions = {module = "io.kotest:kotest-assertions-core", version.ref = "kotest"}
kotest-property = {module = "io.kotest:kotest-property", version.ref = "kotest"}

[bundles]
kotest = ["kotest-framework", "kotest-datatest", "kotest-assertions", "kotest-property"]
```

**build.gradle.kts**
```kotlin
testing {
    suites {
        configureEach {
            if (this is JvmTestSuite) {
                useJUnitJupiter()

                dependencies {
                    // This does not work.
                    implementation(libs.bundles.kotest)

                    // Workaround
                    libs.bundles.kotest.get().forEach {
                        implementation(it)
                    }
                }
            }
        }
    }
}
```

**Output**
```
e: /Users/victorcardona/test-suite-version-catalog/build.gradle.kts:14:21: None of the following functions can be called with the arguments supplied: 
public operator fun DependencyAdder.invoke(dependencyNotation: CharSequence): Unit defined in org.gradle.kotlin.dsl
public operator fun DependencyAdder.invoke(dependency: Dependency): Unit defined in org.gradle.kotlin.dsl
public operator fun DependencyAdder.invoke(files: FileCollection): Unit defined in org.gradle.kotlin.dsl
public operator fun DependencyAdder.invoke(dependency: Provider<out Dependency>): Unit defined in org.gradle.kotlin.dsl
public operator fun DependencyAdder.invoke(externalModule: ProviderConvertible<out MinimalExternalModuleDependency>): Unit defined in org.gradle.kotlin.dsl
```

### Steps to Reproduce 

1. Create a version catalog that contains a bundle.
2. Configure a test suite in `build.gradle.kts` and attempt to add a dependency to the bundle.
See example at https://github.com/VictorCardona75/test-suite-version-catalog

### Your Environment

Build scan URL:
JDK: Azul Zulu 18.0.2
Gradle: 7.6
Kotlin: either 1.7.10 or 1.8.0
