### ISSUE TITLE
`kotlin-symbolProcessing` can't be adde din `setting.gardle.kts`

### ISSUE THREAD

**Issue by igorwojda** [gradle/gradle#23972]
### Expected Behavior

Dependency for [symbol-processing-gradle-plugin](https://repo.maven.apache.org/maven2/com/google/devtools/ksp/symbol-processing-gradle-plugin ) works in both `libs.versions.toml` and `settings.gradle.kts`  file.

### Current Behavior

The plugin `com.google.devtools.ksp` dependency works fine in the `libs.versions.toml` file, but can't be resolved when the version catalog is defined in the `settings.gradle.kts` file. The  dependency resolution fails:

```
* Exception is:
java.lang.RuntimeException: org.gradle.api.InvalidUserDataException: Invalid catalog definition:
  - Problem: In version catalog libs, version reference '1.7.20.1.0.7' doesn't exist.
    
    Reason: Plugin 'com.google.devtools.ksp' references version '1.7.20.1.0.7' which doesn't exist.    
```

### Context

It looks like the call to `versionRef` under the hood replaces `-` character to `.` character and as a result gradle tries to resolve the non-existing dependency version (`1.7.20.1.0.7` instead of `1.7.20-1.0.7`)

### Steps to Reproduce 

This dependency works fine in the `libs.versions.toml` file:

```toml
[versions]
kotlinSymbolProcessing = "1.7.20-1.0.7"

[plugins]
# Search Gradle Plugins https://plugins.gradle.org/
kotlin-symbolProcessing = { id = "com.google.devtools.ksp", version.ref = "kotlinSymbolProcessing" }
```

However, after defining the same plugin dependency in the `settings.gradle.kts` file...

```kotlin
dependencyResolutionManagement {
    versionCatalogs {
        create("libs") {
            version("kotlinSymbolProcessing", "1.7.20-1.0.7")
            plugin("kotlin-symbolprocessing", "com.google.devtools.ksp").versionRef("1.7.20-1.0.7")
        }
    }
}
```

Tested on Gradle 7.6 and 8.0.1
