### ISSUE TITLE
Passing `org.gradle.testkit.dir` via command line property does not change TestKit working directory

### ISSUE THREAD

**Issue by aSemy** [gradle/gradle#24142]
I am not able to set the TestKit working dir using the `org.gradle.testkit.dir` system property

```shell
./gradlew check \
-D"org.gradle.testkit.dir=/path/to/temp/dir" # this has no effect
```

### Expected Behavior

Either I am able to set the TestKit working dir using the `org.gradle.testkit.dir` system property, as documented:

> https://docs.gradle.org/current/userguide/test_kit.html#sec:controlling_the_build_environment
>
> The TestKit provides two ways to specify a location that is regularly cleaned, such as the project’s build folder:
> 
> * The `org.gradle.testkit.dir` system property;
> * The [`GradleRunner.withTestKitDir(file testKitDir)`](https://docs.gradle.org/current/javadoc/org/gradle/testkit/runner/GradleRunner.html#withTestKitDir-java.io.File-) method.

Alternatively the documentation is updated to be more clear about the purpose and usage of the `org.gradle.testkit.dir` system property.

### Current Behavior

I am not able to set the TestKit working dir using the `org.gradle.testkit.dir` system property

### Context

I am trying to improve the performance of test when run via GitHub Actions. I want to be able to cache the TestKit working directory between different CI runs. [Gradle Build Action](https://github.com/gradle/gradle-build-action) does not cache the TestKit dir, and https://github.com/actions/cache does not allow for 'wildcard' caching, so I can't pass in a path like `**/.gradle-test-kit`.

As a workaround I have to do the following

1. In the GitHub workflow manually set up an environment variable, `GRADLE_TESTKIT_DIR`
    ```yaml
    
    - name: Cache Gradle TestKit
      id: cache-gradle-testkit
      uses: actions/cache@v3
      with:
        path: |
          ${{ runner.temp }}/.gradle-test-kit/caches
        key: gradle-testkit-${{ runner.os }}
    
    - uses: gradle/gradle-build-action@v2
      env:
        GRADLE_TESTKIT_DIR: ${{ runner.temp }}/.gradle-test-kit/caches
      with:
        gradle-home-cache-cleanup: true
        arguments: ${{ inputs.gradle-task }}
    ```
2. In `build.gradle.kts`, pass `GRADLE_TESTKIT_DIR` to my tests via a custom system property
    ```kotlin
    tasks.withType<Test>().configureEach {
      providers.environmentVariable("GRADLE_TESTKIT_DIR").orNull?.let {
        systemProperty("gradleTestKitDir", it)
      }
    }
    ```
3. use `withTestKitDir()` to set the TestKit working dir

    ```kotlin
    val runner = GradleRunner.create()
      .withProjectDir(projectDir)
      .apply {
        System.getProperty("gradleTestKitDir")?.let { 
          withTestKitDir(File(it))
        }
      }
    ```

### Steps to Reproduce

[sample.zip](https://github.com/gradle/gradle/files/10884119/sample.zip)

1. unpackage the project
1. run 
    ```shell
    ./gradlew check -D"org.gradle.testkit.dir=./temp"
    ```
3. The test passes successfully
4. TestKit does not use `./temp` as its working dir
5. TestKit uses `build/tmp/functionalTest/work/.gradle-test-kit`, as its working dir

### Your Environment

Gradle 8.0.1
