### ISSUE TITLE
Document and hint at supported "short" dependency notations when there is no version

### ISSUE THREAD

**Issue by martinbonnin** [gradle/gradle#24169]
The following in a .toml file:

```toml
[libraries]
compose-bom = "androidx.compose:compose-bom:2023.01.00"
compose-ui = "androidx.compose.ui:ui"
```

fails with

```
org.gradle.api.InvalidUserDataException: Invalid TOML catalog definition:
  - Problem: In version catalog libs, on alias 'compose-ui' notation 'androidx.compose.ui:ui' is not a valid dependency notation.
```

One has to use the longer version instead: `compose-ui = { module = "androidx.compose.ui:ui" }`

It would be nice if both were allowed:

```toml
[libraries]
# works
compose-ui = { module = "androidx.compose.ui:ui" }
# works too, same behaviour
compose-ui = "androidx.compose.ui:ui"
```
