### ISSUE TITLE
Obscure error when using `platform()` to align dependencies with a version catalog dependency

### ISSUE THREAD

**Issue by aSemy** [gradle/gradle#24299]
### Expected Behavior

I can set a platform dependency to align versions in a JVM test suite

```kotlin
// build.gradle.kts

plugins {
  java
  `jvm-test-suite`
}

testing.suites {
  withType<JvmTestSuite>().configureEach {
    dependencies {
      // doesn't work:
      implementation(platform(libs.kotlinxSerialization.bom))

      // works:
      //implementation(platform("org.jetbrains.kotlinx:kotlinx-serialization-bom:1.4.1"))

      implementation(libs.kotlinxSerialization.json)
    }
  }
}
```

### Current Behavior

I get an obscure error. It doesn't point to where the problem is, which is not user friendly. 

```
> Task :prepareKotlinBuildScriptModel UP-TO-DATE

* What went wrong:
Could not resolve all dependencies for configuration ':testCompileClasspath'.
Minimal dependencies are immutable.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 82ms
```

[gradle-test-suite-platform.zip](https://github.com/gradle/gradle/files/10951642/gradle-test-suite-platform.zip)

### Steps to Reproduce

```toml
# ./gradle/libs.versions.toml
[versions]
kotlinx-serialization = "1.4.1"

[libraries]

kotlinxSerialization-bom = { module = "org.jetbrains.kotlinx:kotlinx-serialization-bom", version.ref = "kotlinx-serialization" }
kotlinxSerialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json" }
```

```kotlin
// build.gradle.kts
plugins {
  java
  `jvm-test-suite`
}

repositories {
  mavenCentral()
}

testing.suites {
  withType<JvmTestSuite>().configureEach {
    dependencies {
      implementation(platform(libs.kotlinxSerialization.bom))
      //implementation(platform("org.jetbrains.kotlinx:kotlinx-serialization-bom:1.4.1"))
      implementation(libs.kotlinxSerialization.json)
    }
  }
}
```

### Your Environment

Gradle 8.0.2
