### ISSUE TITLE
Incompatible Gradle daemon in Azure Devops

### ISSUE THREAD

**Issue by lars06** [gradle/gradle#24343]
### Expected Behavior
The Gradle daemon should be reused between Azure Devops steps when found

### Current Behavior
Often 1 or 2 daemons are found but show as incompatible, despite same build environment. This is using the Azure Devops [Gradle task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/gradle-v3?view=azure-pipelines), setting the JDK to v17 which corresponds with what's in the toolchain (confirmed in each case that JAVA_HOME=/usr/lib/jvm/temurin-17-jdk-amd64)
```
                    -   task: Gradle@3
                        displayName: Build
                        inputs:
                            gradleWrapperFile: 'gradlew'
                            tasks: 'build'
                            javaHomeOption: 'JDKVersion'
                            jdkVersionOption: '1.17'
```
Locally the daemon runs correctly.

### Steps to Reproduce 
- Create two Azure Devops pipeline tasks as shown above
- On second task, see Gradle start new daemon with incompatibility message
