### ISSUE TITLE
Version Catalogs - Enhanced Platform Support

### ISSUE THREAD

**Issue by austinarbor-wk** [gradle/gradle#26048]
### Expected Behavior

Using a platform in a version catalog seems to add more complexity than it helps eliminate. Take for example the catalog
```toml
[versions]
jackson = "2.14.2"

[libraries]
jackson-bom = { group = "com.fasterxml.jackson", name = "jackson-bom", version.ref = "jackson" }
```

If I want to use the jackson libraries, I have to _also_ add each individual dependency from the BOM. I can exclude the version from the declaration, but then I can't use the library from the catalog without also explicitly using the BOM

Additionally, if I create a `jackson` bundle and include the `jackson-bom` library, this doesn't work as a platform since it is being included as a dependency instead of a platform. So in summary, I think version catalogs are antithetical to platforms when they really should be able to work better together.

I propose adding a new section `[platforms]` to the TOML / version catalog definition
```toml
[platforms]
jackson-bom = { group = "com.fasterxml.jackson", name = "jackson-bom", version.ref = "jackson" }
```
1. After a platform is added, the metadata / dependency information for the platform are looked up
2. During codegen phase, accessors are automatically generated for each dependency in the platform. The generated entries could either be added directly to `libs.`, or a new subgroup `libs.platforms` could be added

```kotlin
dependencies {
   implementation(libs.platforms.jackson.core.jackson.databind) //  generated path?
}
```

### Current Behavior (optional)

In my opinion, there is really no easy way to use platforms when using version catalogs. When using version catalogs, its better to just create a bundle of the dependencies you want to include.

### Context

I think my "Expected Behavior" section describes the context pretty well. Please let me know if anything is confusing and I will be happy to clarify

**Comment by austinarbor-wk** [comment]
@big-guy can you please provide an example of best practices for using platforms in version catalogs? Is it expected that we do something like this?
`libs.versions.toml`:
```toml
[versions]
jackson = "2.14.2"

[libraries]
jackson-bom = { group = "com.fasterxml.jackson", name = "jackson-bom", version.ref = "jackson" }
jackson-databind = { group = "com.fasterxml.jackson.core", name = "jackson-databind" } # note a version is not specified
jackson-module-kotlin = { group = "com.fasterxml.jackson.module", name = "jackson-module-kotlin }
```
`build.gradle.kts`:
```kotlin
dependencies {
  implementation(platform(libs.jackson.bom))
  implementation(libs.jackson.databind)
  implementation(libs.jackson.module.kotlin)
}
```

The above _works_ fine, but, the `jackson-databind` and `jackson-module-kotlin` entries won't work without also importing the bom, and it's impossible to know this unless you look at the toml yourself (even after you look at the toml, there's no way to know what bom you are supposed to import). For a small example like this it's pretty straight forward, but in a spring project there could be dozens or more dependencies for which this applies to.
