### ISSUE TITLE
libs.versions.toml: improve error message when the TOML is invalid

### ISSUE THREAD

**Issue by mvysny** [gradle/gradle#27866]
### Expected Behavior

Evaluating support for version catalogs + `libs.versions.toml`, I did a rookie mistake and forgot to wrap the version number in quotes. Gradle should provide a helpful message, such as: "The version definition for 'dynatest' is invalid: it must be a String yet it was float".

### Current Behavior (optional)

Declaring this TOML in your project:
```toml
[versions]
dynatest = 0.24

[libraries]
dynatest = { module = "com.github.mvysny.dynatest:dynatest", version.ref = "dynatest" }
```
leads to:
```
org.gradle.api.InvalidUserDataException: Invalid TOML catalog definition:
  - Alias definition 'dynatest' is invalid
```
I'm not sure in what way the alias definition is invalid; I don't see any alias in my file so the word 'alias' itself feels misleading.

### Context

The correct TOML file:
```toml
[versions]
dynatest = "0.24"

[libraries]
dynatest = { module = "com.github.mvysny.dynatest:dynatest", version.ref = "dynatest" }
```
