### ISSUE TITLE
jvm-test-suite - support depencency bundles

### ISSUE THREAD

**Issue by jakobrahm** [gradle/gradle#30290]
### Expected Behavior

I assumed that this setup would work:

libs.versions.toml
```toml
[libraries]
spring-test = { module = "org.springframework.boot:spring-boot-starter-test" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }

[bundles]
spring-test = ["spring-test", "junit-jupiter-api", "junit-jupiter-engine"]
```

build.gradle.kts
```kts
testing {
    suites {
        register<JvmTestSuite>("integrationTest") {
            useJUnitJupiter()

            dependencies {
                implementation(libs.bundles.spring.test)
            }
        }
    }
}
```

### Current Behavior (optional)

It seems like you'll have to include all depenencies individually like:
 
libs.versions.toml
```toml
[libraries]
spring-test = { module = "org.springframework.boot:spring-boot-starter-test" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }
```

build.gradle.kts
```kts
testing {
    suites {
        register<JvmTestSuite>("integrationTest") {
            useJUnitJupiter()

            dependencies {
                implementation(libs.spring.test)
                implementation(libs.junit.jupiter.api)
                implementation(libs.junit.jupiter.engine)
            }
        }
    }
}
```

### Context

In a multi-project build there are multiple benefits with declaring dependency versions centrally and to be able to bundle them is a great way of streamlining the project configurations. I've managed to do a workaround by extending the `testImplementation` configuration, but as far as I know, it's an anti pattern to use `config.extendsFrom`? Am I missing something obvious?

**Comment by Kaos2121** [comment]
### Solution

#### `libs.versions.toml`

```toml
[libraries]
spring-test = { module = "org.springframework.boot:spring-boot-starter-test" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }

[bundles]
spring-test-bundle = ["spring-test", "junit-jupiter-api", "junit-jupiter-engine"]
```

#### `build.gradle.kts`

```kotlin
testing {
    suites {
        register<JvmTestSuite>("integrationTest") {
            useJUnitJupiter()

            dependencies {
                implementation(libs.bundles.spring.test.bundle.get())
            }
        }
    }
}
```

### What's Happening?

- **Bundle Defined**: You create a `spring-test-bundle` in `libs.versions.toml`.
- **Bundle Applied**: In your `build.gradle.kts`, you apply that bundle to your `integrationTest` suite.

This approach keeps your dependencies centralized and clean. If you prefer, you can extend `testImplementation`, but using bundles like this is generally more maintainable.
