### ISSUE TITLE
Share versions in multiple toml files

### ISSUE THREAD

**Issue by todoFixIt** [gradle/gradle#31014]
### Expected Behavior

To be able to share versions across multiple toml files.

### Current Behavior (optional)

Currently you can't share versions between catalogs and you can't create a single catalog from multiple toml files neither.

### Context

The reason for this is **to avoid monolithic toml files hard to read**, an example of this would be a Kotlin Multiplaform utils library with hundreds of lines. Currently the choice would be either:
* A -> Having a single toml with comments (this is so hard to read, I'm separating by platform, testing and enterprise libs, it is a mess)
* B -> Having multiple toml, but being each one of those a single catalog, shared versions (like kotlin for example) would be redeclared and that goes against the purpose of having the catalogs to begin with and is prone to error.

Using hacks for this is not good, IDE doesn't hint you about version updates, and as always you'll find bugs/issues on future gradle updates since there is no official support for this.

**Comment by ljacomet** [comment]
From what you describe, it seems that it could be solved by having a single catalog that would contain all the Kotlin libraries that share a common version.

Could you explain why the above is not a valid solution for you? Could you share some concrete examples of the kind of things you would organize in multiple catalogs but need a shared version for?

**Comment by todoFixIt** [comment]
> From what you describe, it seems that it could be solved by having a single catalog that would contain all the Kotlin libraries that share a common version.
> 
> Could you explain why the above is not a valid solution for you? Could you share some concrete examples of the kind of things you would organize in multiple catalogs but need a shared version for?

A single catalog is not what I need, **I need a catalog per platform: JVM, Android, iOS..., a catalog for enterprise libraries**, and if I'm making a library I would want a separate **one just for the libs/plugins declared ONLY for the sample project.** Also I will be grouping with comments inside each one of those catalogs the testing libraries. 

**The issue is that many versions will be the same across those catalogs and redeclaring them makes no sense and is error prone.**

Any KMP library that has platform specific dependencies share the same version for all of those dependencies, **this is not a corner case is a common one (at least in KMP)**.

A **KMP toml** for KMP libraries and plugins

```toml
[versions]
kotlin = "2.0.21"
cryptographyCore = "0.4.0"

[libraries]
cryptography-provider-apple = { module = "dev.whyoleg.cryptography:cryptography-provider-apple", version.ref = "cryptographyCore" }

# Testing
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

[plugins]
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
```

A **JVM** toml for JVM libraries and plugins. **You can see cryptographyCore is redeclared here**

```toml
[versions]
cryptographyCore = "0.4.0"

[libraries]
cryptography-provider-jdk = { module = "dev.whyoleg.cryptography:cryptography-provider-jdk", version.ref = "cryptographyCore" }

# Testing
junit = { group = "junit", name = "junit", version.ref = "junit" }

[plugins]
```

This gives me control over what goes in the final compilation (grouping the testing ones) an easy grasp of specific platform dependencies so as time goes by we could be migrating some of those specific libraries for official JetBrains, Google or very used third party libraries, also if a new platform is added (Web) we could see which dependencies are platform specific and what needs to be created for that new platform and which libs we could base our solution in if non existing sotware for it yet (already happen). This also gives us control over our own software and what to prioritize, if wee need a fix or update for some specific libs, or some CI related stuff we wont be needing to see the sample project stuff since is not very important. 

**All of this in a single catalog is just a mess., can't group properly with comments since there are 3 separate sections (versions, libraries and plugins) also the scrolling...**
