### ISSUE TITLE
Add public API that allows access to generated typesafe project accessors

### ISSUE THREAD

**Issue by ivanalvarado** [gradle/gradle#32602]
### Expected Behavior

Add a public API that allows access to generated typesafe project accessors. Similar to the way we can access the aliases for Version Catalogs with the following:

If we had the following version catalogs in `libs.versions.toml`:
```toml
[versions]
accompanist = "0.37.0"
androidDesugarJdkLibs = "2.1.4"

[libraries]
accompanist-permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanist" }
android-desugarJdkLibs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "androidDesugarJdkLibs" }
```

the following code snippet would yield:

```kotlin
val catalogs = project.extensions.findByType(VersionCatalogsExtension::class.java) ?: return

catalogs.catalogNames.forEach { catalogName -> 
    val catalog = catalogs.named(catalogName) // e.g. catalogName = "libs"
    val catalog.libraryAliases.forEach { alias ->
        println("alias: $alias")
    }
}
```

Output:
```
alias: accompanist.permissions
alias: android.desugarJdkLibs
```

Thus, Gradle [provides an API that allows access to the transformed aliases](https://github.com/gradle/gradle/blob/master/subprojects/core-api/src/main/java/org/gradle/api/artifacts/VersionCatalog.java#L76-L85)

I'm requesting something very similar, but for typesafe project accessors where the API returns the _generated_ project accessors:
- `:feature:foo-bar:baz` // Project path
- `projects.feature.fooBar.baz` // Corresponding project accessor - RETURN THIS

To my knowledge, no Gradle API provides access to these generated project accessors at the moment. [Hinge has developed a plugin that generates the _expected_ project accessors notation](https://github.com/Hinge/project-accessors/blob/main/project-accessors/src/main/kotlin/co/hinge/gradle/projectaccessors/ProjectAccessorsGenerator.kt) by following this documentation section:

> Project accessors are based on project paths. For instance, the path :commons:utils:some:lib becomes projects.commons.utils.some.lib, while kebab-case (some-lib) and snake-case (some_lib) are converted to camel case: projects.someLib.

but, I would rather depend on an API that is maintained by Gradle itself to ensure correctness.

### Current Behavior (optional)

Not supported, to my knowledge.

### Context

I'm trying to add support for outputting the advice from the [DAGP](https://github.com/autonomousapps/dependency-analysis-gradle-plugin) in typesafe project accessors format, rather than the default `project(":feature:foo-bar:baz")`.

The motivation is, DAGP has a `fixDependencies` task that will rewrite your gradle script's dependencies block based on the advice it produces. As you can imagine, we can run `fixDependencies` for the entire project and have it completely adhere to DAGP's recommendation. But, if your project uses typesafe accessors, you have to manually go and update the project dependencies to the accessors format.
Here's the PR for additional context: https://github.com/autonomousapps/dependency-analysis-gradle-plugin/pull/1189
