### ISSUE TITLE
Error while setting file permissions under `~/.gradle`

### ISSUE THREAD

**Issue by pbzdyl** [gradle/gradle#8673]
I am getting the following error:

```
Caused by: org.gradle.internal.nativeintegration.filesystem.FileException: Could not set file mode 700 on '/root/.gradle/daemon/4.10.2'.
	at org.gradle.internal.nativeintegration.filesystem.services.GenericFileSystem.chmod(GenericFileSystem.java:90)
	at org.gradle.cache.internal.SimpleStateCache.serialize(SimpleStateCache.java:117)
 	... 41 more
Caused by: net.rubygrapefruit.platform.NativeException: Could not set UNIX mode on /root/.gradle/daemon/4.10.2: could not chmod file (errno 1: Operation not permitted)
	at net.rubygrapefruit.platform.internal.DefaultPosixFiles.setMode(DefaultPosixFiles.java:61)
	at org.gradle.internal.nativeintegration.filesystem.services.NativePlatformBackedChmod.chmod(NativePlatformBackedChmod.java:33)
	at org.gradle.internal.nativeintegration.filesystem.services.GenericFileSystem.chmod(GenericFileSystem.java:88)
	... 42 more
```

when the `~/.gradle` and subdirectories are not owned by the current user but they have necessary permissions set for the current user to use them.

### Expected Behavior
Gradle doesn't change file permissions unnecessarily and works in the environment described in detail below.

### Current Behavior
Gradle tries to change file permissions on files under `~/.gradle` even if it's not necessary.

### Context
I am using BitBucket Pipelines running Gradle wrapper inside of docker container and using Pipelines caching.

### Steps to Reproduce (for bugs)

I have created a repository reproducing the issue: https://bitbucket.org/badyl/gradle-bitbucket-pipelines-issue

As you can see in the pipelines build configuration gradle cache directory `$BITBUCKET_CLONE_DIR/.caches/gradle` is mounted as a volume in docker container running the build under `/root/.gradle`. Due to security reasons BitBucket Pipelines mounts that directory using `Uid: (65534/  nobody)   Gid: (65534/ nogroup)` and the build in the docker container is using `root` user, thus I'm running `chmod -R a+rwX $BITBUCKET_CLONE_DIR/.caches/gradle` to grant necessary permissions to the cached gradle files (all users can write to files and directories and all users can change into all subdirectories).

When [the first build is run](https://bitbucket.org/badyl/gradle-bitbucket-pipelines-issue/addon/pipelines/home#!/results/1) everything works fine and the `~/.gradle` directory is being cached by BitBucket Pipelines.

However, [during the next build](https://bitbucket.org/badyl/gradle-bitbucket-pipelines-issue/addon/pipelines/home#!/results/2) Gradle tries to change file permissions for the already existing directory `/root/.gradle/daemon/4.10.2` (coming from the previous build cache) which results in `Could not set UNIX mode on /root/.gradle/daemon/4.10.2: could not chmod file (errno 1: Operation not permitted)` as the `root` is not the owner of the `/root/.gradle/daemon/4.10.2` directory:

```
+ stat /root/.gradle/daemon/4.10.2
  File: /root/.gradle/daemon/4.10.2
  Size: 4096      	Blocks: 8          IO Block: 4096   directory
Device: 97fh/2431d	Inode: 5389438     Links: 2
Access: (0777/drwxrwxrwx)  Uid: (65534/  nobody)   Gid: (65534/ nogroup)
Access: 2019-03-04 09:18:51.462943292 +0000
Modify: 2019-03-04 09:18:44.005767681 +0000
Change: 2019-03-04 09:18:51.462943292 +0000
 Birth: -
```

On the other hand Gradle doesn't need to change the file permissions as it already can use the existing directory to store its cached files: `Access: (0777/drwxrwxrwx)  Uid: (65534/  nobody)   Gid: (65534/ nogroup)`.

**Comment by lacasseio** [comment]
I can see how this is causing issues. However, I'm unsure if you should be caching everything under the `.gradle` directory. Here is a [Travis CI example](https://github.com/gradle-guides/creating-new-gradle-builds/blob/master/.travis.yml#L5-L12) that I believe correctly cache the `.gradle/`. There's also lock files under the `.gradle` directory which I don't believe should be part of the cache. Let me get more information on this use-case and comment here.

**Comment by pbzdyl** [comment]
Thank you for your suggestion @lacasseio. I was able to fix the issue by using the following [BitBucket Pipelines configuration](https://bitbucket.org/badyl/gradle-bitbucket-pipelines-issue/src/c8d9c0cb838d774860d3d225e9dee6ff197f7cb9/bitbucket-pipelines.yml):

```
pipelines:
  custom:
    gradle-test:
      - step:
          name: Gradle file permission issue
          services:
            - docker
          caches:
            - docker
            - gradlewrapperindocker
            - gradlecachesindocker
          script:
            - set -x
            - mkdir -p .gradle/wrapper .gradle/caches
            - chmod -R a+rwX .gradle
            - docker run --volume $BITBUCKET_CLONE_DIR:/app:rw --workdir /app --volume $BITBUCKET_CLONE_DIR/.gradle/wrapper:/root/.gradle/wrapper:rw --volume $BITBUCKET_CLONE_DIR/.gradle/caches:/root/.gradle/caches:rw openjdk:8 sh -c 'set -x; ./gradlew --debug --full-stacktrace build'
          after-script:
            - set -x
            - rm -f  .gradle/caches/modules-2/modules-2.lock
            - rm -fr .gradle/caches/*/plugin-resolution/
definitions:
  caches:
    gradlewrapperindocker: .gradle/wrapper
    gradlecachesindocker: .gradle/caches
```
